language: python
install:
  - pip install -r requirements.txt
script:
  - black --check .
  - flake8 --max-line-length=150 .
  - coverage run manage.py test
after_script:
  - coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: $accesskeyid
  secret_access_key: $secretaccesskey
  region: us-east-1
  app: mysite
  env: mysite-dev7
  bucket_name: elasticbeanstalk-us-east-1-053788421837
  on:
    repo: ivarfan/nyu6063hw
    branch: master
  skip_cleanup: 'true'